version: '3'
services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
    ports:
      - "54320:5432"